spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/student_system_management
    username: postgres
    password: Emanuele00
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      jdbc:
        lob:
          '[non_contextual_creation]': true
      hibernate:
        '[format_sql]': true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  thymeleaf:
    check-template-location: false
